In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import joblib

In [6]:
data=pd.read_csv('ASD.csv')
data.head(3)

,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,Age_Mons,Sex,Jaundice,Family_mem_with_ASD,Who completed the test,outcome
0,0,0,0,0,0,0,1,1,0,1,28,0,1,0,1,0
1,1,1,0,0,0,1,1,0,0,0,36,1,1,0,1,1
2,1,0,0,0,0,0,1,1,0,1,36,1,1,0,1,1

In [7]:
data.isnull().sum()

A1                        0
A2                        0
A3                        0
A4                        0
A5                        0
A6                        0
A7                        0
A8                        0
A9                        0
A10                       0
Age_Mons                  0
Sex                       0
Jaundice                  0
Family_mem_with_ASD       0
Who completed the test    0
outcome                   0
dtype: int64

In [8]:
data.describe()

,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,Age_Mons,Sex,Jaundice,Family_mem_with_ASD,Who completed the test,outcome
count,1047.000000,1047.000000,1047.000000,1047.000000,1047.000000,1047.000000,1047.000000,1047.000000,1047.000000,1047.000000,1047.000000,1047.000000,1047.000000,1047.000000,1047.000000,1047.000000
mean,0.563515,0.446991,0.400191,0.511939,0.523400,0.576886,0.648520,0.458453,0.490926,0.585482,27.851003,0.698185,0.274117,0.162369,0.972302,0.689589
std,0.496186,0.497420,0.490171,0.500096,0.499691,0.494289,0.477661,0.498509,0.500157,0.492874,7.978506,0.459265,0.446281,0.368965,0.164185,0.462883
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,23.000000,0.000000,0.000000,0.000000,1.000000,0.000000
50%,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,30.000000,1.000000,0.000000,0.000000,1.000000,1.000000
75%,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,36.000000,1.000000,1.000000,0.000000,1.000000,1.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,36.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [10]:
#SPLITTING TEST AND TRAIN DATA
X = data.drop(columns='outcome ', axis=1)
Y = data['outcome ']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.35, stratify=Y, random_state=2)

In [11]:
from sklearn.ensemble import RandomForestClassifier
RFClassifierModelASD = RandomForestClassifier(random_state=5)
RFClassifierModelASD.fit(X_train, Y_train)

RandomForestClassifier(random_state=5)

In [12]:
X_train_predict = RFClassifierModelASD.predict(X_train)
train_accuracy = accuracy_score( np.round(abs(X_train_predict)), Y_train )

X_test_predict = RFClassifierModelASD.predict(X_test)
test_accuracy = accuracy_score(np.round(abs(X_test_predict)) ,Y_test)

print('Training data Accuracy: ', train_accuracy*100 ,'%')
print('Test data Accuracy: ', test_accuracy*100 ,'%')

Training data Accuracy:  100.0 %
Test data Accuracy:  95.91280653950953 %

In [13]:
joblib.dump(RFClassifierModelASD,'RFClassifierModelASD.pkl')

['RFClassifierModelASD.pkl']

In [18]:
input_data = (1,1,1,0,1,0,1,1,0,1,12,1,0,0,1)
# change the input data to a numpy array
input_data_as_numpy_array= np.asarray(input_data)
# reshape the numpy array as we are predicting for only on instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)
PredictModelRFC = RFClassifierModelASD.predict(input_data_reshaped)


#questions
print(PredictModelRFC[0])
if (PredictModelRFC[0]== 0):
  print('No')
else:
  print('yes')

1
yes

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(